import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import "./globals.css";

const giaSerifDisplay = localFont({
  src: './fonts/GiaSerifDisplay.woff2',
  variable: '--font-display',
  display: 'swap',
});

const dmSans = DM_Sans({
  variable: '--font-sans',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${giaSerifDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
